[[bind]]
action = "RevealMap"
key = "R"

[[bind]]
action = "ToggleDebug"
key = "F3"

[[bind]]
action = "WalkNorth"
keys = ["K", "Numpad8"]

[[bind]]
action = "WalkEast"
keys = ["L", "Numpad6"]

[[bind]]
action = "WalkSouth"
keys = ["J", "Numpad2"]

[[bind]]
action = "WalkWest"
keys = ["H", "Numpad4"]

[[bind]]
action = "WalkNortheast"
keys = ["I", "Numpad9"]

[[bind]]
action = "WalkSoutheast"
keys = ["M", "Numpad3"]

[[bind]]
action = "WalkSouthwest"
keys = ["N", "Numpad1"]

[[bind]]
action = "WalkNorthwest"
keys = ["U", "Numpad7"]

[[bind]]
action = "ZoomOut"
keys = ["Minus"]

[[bind]]
action = "ZoomIn"
keys = ["Equals"]
