[[bind]]
action = "ToggleDebug"
key = "F3"

[[bind]]
action = "WalkNorth"
keys = ["W", "Numpad8", "Up"]

[[bind]]
action = "WalkEast"
keys = ["D", "Numpad6", "Right"]

[[bind]]
action = "WalkSouth"
keys = ["S", "Numpad2", "Down"]

[[bind]]
action = "WalkWest"
keys = ["A", "Numpad4", "Left"]

[[bind]]
action = "ZoomOut"
keys = ["Minus"]

[[bind]]
action = "ZoomIn"
keys = ["Equals"]
